SELECT FP.CATEGORY, FP.PRICE AS MAX_PRICE, FP.PRODUCT_NAME
FROM FOOD_PRODUCT FP
INNER JOIN (
    SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
    GROUP BY CATEGORY
) AS MAX_FOOD
ON FP.CATEGORY = MAX_FOOD.CATEGORY AND FP.PRICE = MAX_FOOD.MAX_PRICE
ORDER BY FP.PRICE DESC;
